"""CONFIG.json 规范模型、归一化与运行时投影。"""

from app.config.document import (
    CanonicalConfigDocument,
    ConfigDomainModel,
    McpDomainModel,
    McpServerCanonicalModel,
    default_config_domain_dict,
    empty_canonical_document,
)
from app.config.modules import (
    MODULE_DISPLAY_NAMES,
    MODULE_MODELS,
    ORDINARY_MODULE_KEYS,
    USER_VISIBLE_MODULE_KEYS,
    AgentModule,
    ContextModule,
    MiddlewareModule,
    SkillsModule,
    TelemetryModule,
    ToolsModule,
    default_module_value,
    is_ordinary_module,
    is_user_visible_module,
    validate_module_value,
)
from app.config.normalize import (
    ConfigWarning,
    NormalizedConfigResult,
    merge_module_into_raw,
    normalize_config_document,
    preserve_unknown_fields,
    project_effective_runtime_config,
    project_module_for_api,
    redact_mapping_secrets,
)

__all__ = [
    "AgentModule",
    "CanonicalConfigDocument",
    "ConfigDomainModel",
    "ConfigWarning",
    "ContextModule",
    "MODULE_DISPLAY_NAMES",
    "MODULE_MODELS",
    "McpDomainModel",
    "McpServerCanonicalModel",
    "MiddlewareModule",
    "NormalizedConfigResult",
    "ORDINARY_MODULE_KEYS",
    "USER_VISIBLE_MODULE_KEYS",
    "SkillsModule",
    "TelemetryModule",
    "ToolsModule",
    "default_config_domain_dict",
    "default_module_value",
    "empty_canonical_document",
    "is_ordinary_module",
    "is_user_visible_module",
    "merge_module_into_raw",
    "normalize_config_document",
    "preserve_unknown_fields",
    "project_effective_runtime_config",
    "project_module_for_api",
    "redact_mapping_secrets",
    "validate_module_value",
]
